In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as scp

In [2]:
dataset = pd.read_csv('/kaggle/input/students-drop-out-prediction/train.csv')
dataset.shape

(3796, 43)

In [3]:
X = dataset[dataset.columns[:-1]]
y = dataset[dataset.columns[-1]]
X.shape, y.shape

((3796, 42), (3796,))

In [4]:
binary_list = ['v_1', 'v_26', 'v_11', 'v_14', 'v_30', 'v_28', 'v_9', 'v_27']
nominal_list = ['v_32', 'v_4', 'v_3', 'v_20', 'v_21', 'v_18', 'v_25', 'v_12']
ordinal_list = ['v_31', 'v_15', 'v_19', 'v_13', 'v_33', 'v_17', 'v_29', 'v_23', 'v_6', 'v_24', 'v_10', 'v_5', 'v_22', 'v_0']
ratio_list = ['v_16', 'v_2', 'v_8', 'v_7', 'v_34', 'v_35', 'v_36', 'v_37', 'v_38', 'v_39', 'v_40']
id_list = ['id']
final_list = id_list + sorted(binary_list) + sorted(nominal_list) + sorted(ordinal_list) + sorted(ratio_list)
final_list

['id',
 'v_1',
 'v_11',
 'v_14',
 'v_26',
 'v_27',
 'v_28',
 'v_30',
 'v_9',
 'v_12',
 'v_18',
 'v_20',
 'v_21',
 'v_25',
 'v_3',
 'v_32',
 'v_4',
 'v_0',
 'v_10',
 'v_13',
 'v_15',
 'v_17',
 'v_19',
 'v_22',
 'v_23',
 'v_24',
 'v_29',
 'v_31',
 'v_33',
 'v_5',
 'v_6',
 'v_16',
 'v_2',
 'v_34',
 'v_35',
 'v_36',
 'v_37',
 'v_38',
 'v_39',
 'v_40',
 'v_7',
 'v_8']

In [5]:
X_transformed = X[final_list]
X_transformed.head()

id  v_1  v_11  v_14  v_26  v_27  v_28  v_30  v_9  v_12  ...  v_2  v_34  \
0   0    1     1     0     0     1     0     0    0    16  ... -0.3     1   
1   1    1     0     1     1     0     0     1    1    22  ...  5.4     6   
2   2    1     1     0     0     1     0     1    0    16  ...  0.6     1   
3   3    1     1     0     0     1     0     0    1    16  ...  0.6     7   
4   4    1     0     0     1     0     0     1    1    22  ...  8.4    16   

   v_35  v_36  v_37  v_38  v_39  v_40   v_7  v_8  
0    93    47     1    48    26     0  13.9    1  
1    29    37    25    53    35     7  14.9    4  
2     8    34     4    43    38     2  11.1    1  
3    37    40    27    43    65     0  11.1    1  
4    22    25    25    24    23     1  10.9   17  

[5 rows x 42 columns]

In [6]:
X_transformed = X_transformed.drop(columns='id')

In [7]:
X_transformed.head()

v_1  v_11  v_14  v_26  v_27  v_28  v_30  v_9  v_12  v_18  ...  v_2  v_34  \
0    1     1     0     0     1     0     0    0    16    30  ... -0.3     1   
1    1     0     1     1     0     0     1    1    22   199  ...  5.4     6   
2    1     1     0     0     1     0     1    0    16    30  ...  0.6     1   
3    1     1     0     0     1     0     0    1    16    23  ...  0.6     7   
4    1     0     0     1     0     0     1    1    22   106  ...  8.4    16   

   v_35  v_36  v_37  v_38  v_39  v_40   v_7  v_8  
0    93    47     1    48    26     0  13.9    1  
1    29    37    25    53    35     7  14.9    4  
2     8    34     4    43    38     2  11.1    1  
3    37    40    27    43    65     0  11.1    1  
4    22    25    25    24    23     1  10.9   17  

[5 rows x 41 columns]

In [8]:
count0 = 0
count1 = 0
count2 = 0
for i in y:
    if i == 0:
        count0+=1
    if i == 1:
        count1+=1
    if i == 2:
        count2+=1
count0, count1, count2

(1243, 1863, 690)

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [10]:
'''from sklearn.feature_selection import SelectFpr
s_fpr_ss = SelectFpr(alpha=0.075)
s_fpr_mm = SelectFpr(alpha=0.075)
X_train_ss = s_fpr_ss.fit_transform(X_transformed, y)
X_train_mm = s_fpr_mm.fit_transform(X_transformed, y)'''

'from sklearn.feature_selection import SelectFpr\ns_fpr_ss = SelectFpr(alpha=0.075)\ns_fpr_mm = SelectFpr(alpha=0.075)\nX_train_ss = s_fpr_ss.fit_transform(X_transformed, y)\nX_train_mm = s_fpr_mm.fit_transform(X_transformed, y)'

In [11]:
rfc = RandomForestClassifier(max_depth=30, min_samples_split=15, n_estimators=100, class_weight=None, random_state=25)
cross_val_score(rfc, X_transformed, y, scoring='f1_micro', cv=5)

array([0.74868421, 0.72990777, 0.72859025, 0.74176548, 0.73781291])

In [12]:
from sklearn.feature_selection import SelectFpr
s_fpr = SelectFpr(alpha=0.001)
X_train = s_fpr.fit_transform(X_transformed, y)

In [13]:
rfc = RandomForestClassifier(max_depth=30, min_samples_split=15, n_estimators=100, class_weight=None, random_state=25)
cross_val_score(rfc, X_train, y, scoring='f1_micro', cv=5)

array([0.74210526, 0.74176548, 0.73386034, 0.74044796, 0.75757576])

In [14]:
rfc = RandomForestClassifier(max_depth=20, min_samples_split=15, n_estimators=100, class_weight=None, random_state=25)
cross_val_score(rfc, X_train, y, scoring='f1_micro', cv=5)

array([0.74473684, 0.743083  , 0.73649539, 0.73913043, 0.75757576])

In [15]:
'''from sklearn.model_selection import GridSearchCV
rfc = RandomForestClassifier(random_state=25)
model_rfc = GridSearchCV(rfc, {'max_depth':[15,20,25,30], 'min_samples_split':[15,30,45,60], 'n_estimators':[100,200,300], 'class_weight':[None, 'balanced']}, cv=5)
model_rfc.fit(X_train, y)'''

"from sklearn.model_selection import GridSearchCV\nrfc = RandomForestClassifier(random_state=25)\nmodel_rfc = GridSearchCV(rfc, {'max_depth':[15,20,25,30], 'min_samples_split':[15,30,45,60], 'n_estimators':[100,200,300], 'class_weight':[None, 'balanced']}, cv=5)\nmodel_rfc.fit(X_train, y)"

In [16]:
'''model_rfc.best_params_'''

'model_rfc.best_params_'

In [17]:
'''from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
model_knn = GridSearchCV(knn, {'n_neighbors':list(range(3,51)), 'weights':['uniform','distance'], 'algorithm':['auto','ball_tree','kd_tree','brute']})
model_knn.fit(X_train, y)'''

"from sklearn.neighbors import KNeighborsClassifier\nknn = KNeighborsClassifier()\nmodel_knn = GridSearchCV(knn, {'n_neighbors':list(range(3,51)), 'weights':['uniform','distance'], 'algorithm':['auto','ball_tree','kd_tree','brute']})\nmodel_knn.fit(X_train, y)"

In [18]:
'''model_knn.best_params_'''

'model_knn.best_params_'

In [19]:
rfc = RandomForestClassifier(max_depth=20, min_samples_split=15, n_estimators=100, random_state=25)
cross_val_score(rfc, X_train, y, scoring='f1_micro', cv=5)

array([0.74473684, 0.743083  , 0.73649539, 0.73913043, 0.75757576])

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(algorithm='kd_tree', n_neighbors=8, weights='distance')
cross_val_score(knn, X_train, y, scoring='f1_micro', cv=5)

array([0.62105263, 0.62582345, 0.62582345, 0.63636364, 0.62318841])

In [21]:
dataset = pd.read_csv('/kaggle/input/students-drop-out-prediction/test.csv')
dataset.shape

(1628, 42)

In [22]:
X_test=dataset
binary_list = ['v_1', 'v_26', 'v_11', 'v_14', 'v_30', 'v_28', 'v_9', 'v_27']
nominal_list = ['v_32', 'v_4', 'v_3', 'v_20', 'v_21', 'v_18', 'v_25', 'v_12']
ordinal_list = ['v_31', 'v_15', 'v_19', 'v_13', 'v_33', 'v_17', 'v_29', 'v_23', 'v_6', 'v_24', 'v_10', 'v_5', 'v_22', 'v_0']
ratio_list = ['v_16', 'v_2', 'v_8', 'v_7', 'v_34', 'v_35', 'v_36', 'v_37', 'v_38', 'v_39', 'v_40']
id_list = ['id']
final_list = id_list + sorted(binary_list) + sorted(nominal_list) + sorted(ordinal_list) + sorted(ratio_list)
X_test = X_test[final_list]
X_test.head()

id  v_1  v_11  v_14  v_26  v_27  v_28  v_30  v_9  v_12  ...   v_2  v_34  \
0   0    1     1     0     0     0     0     1    0    23  ...  10.4     4   
1   1    1     1     0     0     0     0     1    0    19  ...   0.5    15   
2   2    1     1     0     0     1     0     1    0    16  ...   2.6     4   
3   3    1     1     0     0     1     0     0    1    16  ...   0.6     4   
4   4    1     1     0     0     1     0     0    0    16  ...   2.6     7   

   v_35  v_36  v_37  v_38  v_39  v_40   v_7  v_8  
0    96    36    34    23    72     5  10.8    8  
1    78    12    25    27    67    12  19.4    5  
2    81    47    30    54    23     4   7.6    1  
3   100     6    23    12    28     1  11.1    1  
4    97    25    30    18    52     0   7.6    1  

[5 rows x 42 columns]

In [23]:
X_test = X_test.drop(columns='id')
X_test.head()

v_1  v_11  v_14  v_26  v_27  v_28  v_30  v_9  v_12  v_18  ...   v_2  v_34  \
0    1     1     0     0     0     0     1    0    23   108  ...  10.4     4   
1    1     1     0     0     0     0     1    0    19   261  ...   0.5    15   
2    1     1     0     0     1     0     1    0    16   103  ...   2.6     4   
3    1     1     0     0     1     0     0    1    16   103  ...   0.6     4   
4    1     1     0     0     1     0     0    0    16    12  ...   2.6     7   

   v_35  v_36  v_37  v_38  v_39  v_40   v_7  v_8  
0    96    36    34    23    72     5  10.8    8  
1    78    12    25    27    67    12  19.4    5  
2    81    47    30    54    23     4   7.6    1  
3   100     6    23    12    28     1  11.1    1  
4    97    25    30    18    52     0   7.6    1  

[5 rows x 41 columns]

In [24]:
test_set = s_fpr.transform(X_test)

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=20, min_samples_split=15, n_estimators=100, random_state=25)
rfc.fit(X_train, y)
y_pred = rfc.predict(test_set)
y_pred.shape

(1628,)

In [26]:
predictions = pd.DataFrame(y_pred)
predictions.to_csv('submission.csv', index_label='id', header=['label'])